version: '3.9'

services:
  nginx:
    image: nginx:mbaanni
    build: requirements/nginx
    container_name: nginx
    depends_on:
     - wordpress
    volumes:
      - wordpress:/var/www/http
    ports:
      - 443:443
    networks:
      - testo
    env_file:
      - .env
    restart: always

  wordpress:
    image: wordpress:mbaanni
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/http
    networks:
      - testo
    env_file:
      - .env
    restart: always

  mariadb:
    image: mariadb:mbaanni
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - testo
    env_file:
      - .env
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/mbaanni/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/mbaanni/data/mariadb
      o: bind

networks:
  testo:
    driver: bridge
