version: '3'

services:
  nginx:
    image: nginx:mbaanni
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
      - adminer
    volumes:
      - wordpress:/var/www/http
    ports:
      - 443:443
    networks:
      - testo
    env_file:
      - .env
    restart: always

  wordpress:
    image: wordpress:mbaanni
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/http
    networks:
      - testo
    env_file:
      - .env
    restart: always

  mariadb:
    image: mariadb:mbaanni
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - testo
    env_file:
      - .env
    restart: always

  adminer:
    image: adminer:mbaanni
    container_name: adminer
    build: ./requirements/bonus/adminer/
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/http
    networks:
      - testo
    env_file:
      - .env
    restart: always

  website:
    image: website:mbaanni
    container_name: website
    build: ./requirements/bonus/website/
    networks:
      - testo
    env_file:
      - .env
    restart: always


  ftp:
    image: ftp:mbaanni
    container_name: ftp
    build: ./requirements/bonus/ftp
    volumes:
      - wordpress:/var/www/http
    ports:
      - 21:21
    networks:
      - testo
    env_file:
      - .env
    restart: always

  redis:
    image: redis:mbaanni
    container_name: redis
    build: ./requirements/bonus/redis/
    volumes:
      - wordpress:/var/www/http
    networks:
      - testo
    restart: always

  cadvisor:
    image: cadvisor:mbaanni
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/
    ports:
      - 8080:8080
    depends_on:
      - nginx
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - testo
    restart: always


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/mbaanni/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/mbaanni/data/mariadb
      o: bind

networks:
  testo:
    driver: bridge
